### ISSUE TITLE
imx219 camera

### ISSUE THREAD

**Issue by arrow53** [compulab-yokneam/meta-bsp-imx8mp#1]
I have a raspberry pi camera plugged into the ucm board via the narrow arducam adapter cable. Not sure which way supposed to be plugged in but I have it facing down. When I use `ucm-imx8m-plus_mipi-csi1-imx219.dtb` I see these 

```
[    6.587506] imx219 4-0010: supply VANA not found, using dummy regulator
[    6.587686] imx219 4-0010: supply VDIG not found, using dummy regulator
[    6.587734] imx219 4-0010: supply VDDL not found, using dummy regulator
[    6.617463] imx219 4-0010: failed to read chip id 219
[    6.618055] imx219: probe of 4-0010 failed with error -5
```

Any ideas on things I should try?

**Comment by vraevsky** [comment]
We were able to make the driver recognize the imx219 camera, but we were not able make it work well.

About the i2c io error) Please have a look at:
https://mediawiki.compulab.com/w/index.php?title=UCM-iMX8M-Plus:_Evaluation_Kit:_Getting_Started
Try change the E18 jumper state.
on/off state =>  [P48 is on / P49 is on].

**Comment by arrow53** [comment]
ok thanks
