### ISSUE TITLE
ucm-imx8m-plus-r2.0 after u-boot branch name change

### ISSUE THREAD

**Issue by hkhalili-ocado** [compulab-yokneam/meta-bsp-imx8mp#10]
Branch `ucm-imx8m-plus-r2.0` has broken after u-boot changes. Even though this is not a development branch but `kirkstone-5.15.71-2.2.0` is (from the README), I can see that the fix has only been applied to the latter. If possible, to avoid disruptions to the customer, could you please always ensure that stable branches remain unbroken when changes are made? Many thanks

**Comment by vraevsky** [comment]
@hkhalili-ocado thanks for reporting on the issue.

**Comment by hkhalili-ocado** [comment]
Issue fixed after old u-boot recipe deleted. Thank you.
