### ISSUE TITLE
custom kernel config

### ISSUE THREAD

**Issue by timnis** [compulab-yokneam/meta-bsp-imx8mp#11]
Hi, how I can apply custom kernel config with yocto kirkstone? I need wireguard kernel module. 

The way I used apply custom kernel config with 5.15.32 not working with this 5.15.71?

**Comment by vraevsky** [comment]
Please have a look at this approach:
https://drive.google.com/file/d/1PSfTcwsJrPNJJ31uIueNSJUN9GbkiPq2/view?usp=share_link

**Comment by timnis** [comment]
Thanks for quick reply. This worked.
