### ISSUE TITLE
[ucm-imx8m-plus-r2.0] sigma-dut and opencv still refer to codeaurora

### ISSUE THREAD

**Issue by samey3** [compulab-yokneam/meta-bsp-imx8mp#13]
It seems that even after migration to nxp-github from codeaurora, it is still attempting to fetch from codeaurora for the sigma-dut and opencv packages. Because of this, starting from a clean build and issuing `bitbake -k imx-image-full` fails.

`ERROR: sigma-dut-git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/utils/sigma-dut;protocol=https;branch=github-qca/master;')`

`ERROR: opencv-4.5.4.imx-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://source.codeaurora.org/external/imx/opencv-imx.git;protocol=https;branch=master;branch=4.5.4_imx;name=opencv')`

I was able to fix this issue for the sources/meta-imx/meta-sdk/recipes-connectivity/sigma-dut/sigma-dut_git.bb by switching the SRC_URI to point to the github repository git://github.com/qca/sigma-dut.git, but have so far been unable to do so for compulab-nxp-bsp/sources/meta-imx/meta-bsp/recipes-support/opencv/opencv_4.5.4.imx.bb.

Can a fix be made for this, or any recommendation on what needs to be changed in opencv_4.5.4.imx.bb in order for it to successfully build?

Thanks!

**Comment by vraevsky** [comment]
Please issue the "kirkstone":
https://github.com/compulab-yokneam/Documentation/blob/master/etc/ca2gh.md#kirkstone

**Comment by samey3** [comment]
Perfect, that worked. Thanks!
