### ISSUE TITLE
Changes needed to support the TPM module?

### ISSUE THREAD

**Issue by citruspress** [compulab-yokneam/meta-bsp-imx8mp#15]
We have an evaluation kit for the imx8 plus with a TPM module. We tried building the kirkstone-2.2.0 branch and there's no TPM device available like /dev/tpm*. Do we need to make any changes to support the TPM module?

We made the following changes in local.conf to get the testing tools (along with adding the required layers) as well:

IMAGE_INSTALL:append = " tpm2-tools libtss2 libtss2-tcti-device libtss2-tcti-mssim tpm2-abrmd tpm2-pkcs11"
DISTRO_FEATURES:append = " security tpm"
MACHINE_FEATURES:append = " tpm"

**Comment by vraevsky** [comment]
Please have a look at:
1) https://github.com/compulab-yokneam/meta-bsp-imx8mp/blob/iot-gate-imx8plus-r2.0/conf/machine/iot-gate-imx8plus.conf#L12
2) https://mediawiki.compulab.com/w/index.php?title=IOT-GATE-IMX8PLUS_and_SBC-IOT-IMX8PLUS:_Debian_Linux:_How-To_Guide#TPM

**Comment by citruspress** [comment]
Thanks. Just tried building the other branch, but got into some trouble. I suspect it's because we're running Ubuntu 22.04 on our build env and I get a warning stating it's not supported yet. That seems to work better with the kirkstone-2.2.0 branch.

I also noticed that it's running an older release than the kirkstone-2.2.0 branch.

Any plans on merging the TPM-related changes with the ones in kirkstone-2.2.0?
