### ISSUE TITLE
imx8plus: kirkstone-2.0.0 still points to source.codeaurora.org

### ISSUE THREAD

**Issue by mirzaCet** [compulab-yokneam/meta-bsp-imx8mp#16]
Is there a plan to fix kirkstone-2.0.0 branch to point to Github, instead of defunct CodeAurora?

`
ERROR: linux-compulab-5.15.32-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://source.codeaurora.org/external/imx/linux-imx.git;protocol=https;branch=lf-5.15.y')
`

Note that the build process explained in README.md is also outdated (NXP manifest source).

btw. I see you fixed the kirkstone-2.2.0 couple a weeks ago. Is it means that 5.15.71 is now your official build?

Thank you!

**Comment by arrow53** [comment]
@mirzaCet it's here

https://github.com/compulab-yokneam/meta-bsp-imx8mp/tree/88e56e9b06e6ee4b7638aad49aa0853131b1734a
