### ISSUE TITLE
imx8plus: flexcan1 not enabled on the kirkstone-2.2.0

### ISSUE THREAD

**Issue by mirzaCet** [compulab-yokneam/meta-bsp-imx8mp#17]
Can you please enable the flexcan1 on the 5.15.71?

The [patch](https://github.com/compulab-yokneam/meta-bsp-imx8mp/blob/kirkstone-2.0.0/recipes-kernel/linux/compulab/5.15.32/imx8mp/0053-compulab-iot-gate-imx8plus-enable-flexcan1.patch)  seems to does the job!

Thank you!

**Comment by vraevsky** [comment]
Done.
