### ISSUE TITLE
create the image within specific required linux kernel

### ISSUE THREAD

**Issue by AminSahebi** [compulab-yokneam/meta-bsp-imx8mp#19]
Hi there,

I've been working on a Compulab device for a while, I faced an issue with the Linux kernel, for some reason we need to have another version of the Linux kernel to be compatible with our application, I appreciate any advice for me on how to build the image within previously released kernels, e.g., Linux kernel 5.4 on yocto kernel recipe,

Many thanks

**Comment by arrow53** [comment]
you can use zeus

https://github.com/compulab-yokneam/meta-bsp-imx8mp/tree/zeus/recipes-kernel/linux

**Comment by AminSahebi** [comment]
Thank you very much.
