### ISSUE TITLE
pcie

### ISSUE THREAD

**Issue by arrow53** [compulab-yokneam/meta-bsp-imx8mp#2]
i can't see pcie devices in the M2 slot. Has this been tested?

**Comment by vraevsky** [comment]
It was tested and works on the latest SB revision. I was able to get access to an NVME media connected to the M2 slot.
I have to talk to the HW engineer in order to provide more details.

**Comment by arrow53** [comment]
oh, I see pcie just isn't enabled in the device tree in zeus but is in later releases. I'm good now. thanks.
