### ISSUE TITLE
Adding kernel command-line parameters

### ISSUE THREAD

**Issue by samey3** [compulab-yokneam/meta-bsp-imx8mp#21]
Hello,
I've been trying to add some kernel command-line parameters in order to enable IO polling for NVMes (nvme.poll_queues=1), however I have had no luck with this. This is on ucm-imx8m-plus-r2.0 branch.

What I've tried:
- Added the parameter in the machine config 'local.conf' using the 'APPEND' keyword: 
`APPEND += "nvme.poll_queues=1"`
- Modified uboot parameters such as 'mmcargs', but these changes seem like they are overwritten at some point.
- Played around with grub.cfg, but again no effect.

'APPEND' seems like the standard way to do this, but it seems like these changes are not taking affect during the build. It appears that perhaps a script is reverting any changes I made to the uboot fields? 

I have been digging into this kernel and compulab's uboot to try and figure out what is going on, but can't seem to get it to work. Is there an alternative recommended way to achieve setting custom kernel command-line parameters?

Thanks for any help!

**Comment by vraevsky** [comment]
Please follow the instructions:
Stop in U-boot and issue: setenv boot_opt nvme.poll_queues=1; saveenv; run bsp_bootcmd
