### ISSUE TITLE
[iot-gate-imx8plus] Kernel device tree incomplete in kirkstone-5.15.71-2.2.0 

### ISSUE THREAD

**Issue by mirzaCet** [compulab-yokneam/meta-bsp-imx8mp#9]
Is there a plan to support following blobs in kirkstone 5.15.71-2.2.0:

```
compulab/iot-gate-imx8plus-m2tpm.dtb
compulab/iot-gate-imx8plus-brkout_pwm_gpio.dtb.dtb (is this a typo?)
```

I had to remove them from KERNEL_DEVICETREE in order to build successfully.
Perhaps the patch from kirkstone-5.15.32-2.0.0 did not include all the files properly?

Thank you!

**Comment by vraevsky** [comment]
Already fixed.
